### ISSUE TITLE
Set up security rule

### ISSUE THREAD

**Issue by pjai0005** [yuwei217/5513assignment4_Team_Nemo#1]
@yuwei217, please look into the setting and add a branch protection rule so that none of us can push changes directly to the main branch. 
kindly refer to the link below for more info 
https://docs.github.com/en/github/administering-a-repository/defining-the-mergeability-of-pull-requests/managing-a-branch-protection-rule

**Comment by Sithajawahar** [comment]
I have not made any changes to the main branch anyway. 
But thanks for the heads up

**Comment by yuwei217** [comment]
Yeah, none of us will push changes directly to the main after the cleaning step. Next time I will try this way if needed.
